function smoke_handoff_contracts()
%SMOKE_HANDOFF_CONTRACTS Check vendored schema and persistent artifacts.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
contractFile = fullfile(projectRoot, ".cursor", "contracts", ...
    "project-template-handoff.schema.yaml");
profileFile = fullfile(projectRoot, "02_PAPER", "config", ...
    "paper-profile.example.yaml");
figurePlanFile = fullfile(projectRoot, "01_IDEA", "figure_plan.md");
claimsFile = fullfile(projectRoot, "01_IDEA", "claims.md");
blogFile = fullfile(projectRoot, "ProjectName_blog.md");
revisionFile = fullfile(projectRoot, "02_PAPER", "revision", ...
    "comment_log.example.yaml");

assert(isfile(contractFile), "Vendored handoff contract is missing.");
assert(isfile(profileFile), "Paper-profile example is missing.");
assert(isfile(blogFile), "Public-narrative template is missing.");
assert(isfile(revisionFile), "Revision comment-log example is missing.");

contractText = string(fileread(contractFile));
profileText = string(fileread(profileFile));
figurePlanText = string(fileread(figurePlanFile));
claimsText = string(fileread(claimsFile));
blogText = string(fileread(blogFile));
revisionText = string(fileread(revisionFile));

assert(contains(contractText, 'version: "2026.07.12"') && ...
        contains(contractText, "sourceSha256:"), ...
    "Vendored contract must declare version and canonical-source hash.");

requiredProfileFields = [ ...
    "contractVersion:", "targetVenue:", "minimumResearchObject:", ...
    "paperSpine:", "primaryInnovationAxis:", "noveltyMode:", ...
    "technicalObjectType:", "narrativeArc:", "lifecycleStage:", ...
    "evidenceBoundary:"];
for k = 1:numel(requiredProfileFields)
    assert(contains(profileText, requiredProfileFields(k)), ...
        "Paper profile is missing field %s.", requiredProfileFields(k));
end

assert(contains(claimsText, "technicalObjectType") && ...
        contains(claimsText, "caseContract") && ...
        contains(claimsText, "requiredEvidenceRoles"), ...
    "Claims must preserve narrative and execution routing fields.");

requiredBlogRoutes = [ ...
    "discovery-first", "mechanism-first", "method-first", ...
    "engineering-first", "validation-first", "boundary-diagnosis"];
for k = 1:numel(requiredBlogRoutes)
    assert(contains(blogText, requiredBlogRoutes(k)), ...
        "Public-narrative template is missing route %s.", ...
        requiredBlogRoutes(k));
end
assert(contains(blogText, "为什么有效") && ...
        contains(blogText, "不自动等于") && ...
        contains(blogText, "新物理机理"), ...
    "Public-narrative template must distinguish explanation layers.");
assert(contains(blogText, "起、承、转、合、升") && ...
        contains(blogText, "工程实际问题") && ...
        contains(blogText, "推荐逻辑"), ...
    "Public narrative must retain the recommended engineering-first arc.");

requiredFigureFields = [ ...
    "figurePlanId", "expectedTrend", "keyFeatureToInspect", ...
    "mechanismToTest", "advantageCriterion", "boundaryTest"];
for k = 1:numel(requiredFigureFields)
    assert(contains(figurePlanText, requiredFigureFields(k)), ...
        "Figure plan is missing field %s.", requiredFigureFields(k));
end

allowedRevisionStatuses = [ ...
    "open", "manuscript-patched", "requires-new-case", ...
    "response-drafted", "verified", "closed"];
for k = 1:numel(allowedRevisionStatuses)
    assert(contains(revisionText, "  - " + allowedRevisionStatuses(k)), ...
        "Revision log is missing status %s.", allowedRevisionStatuses(k));
end

fprintf("HANDOFF_CONTRACT_SMOKE_OK\n");
end
