function smoke_run_contracts()
%SMOKE_RUN_CONTRACTS Check recursive input provenance and tracker outcomes.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(projectRoot);

temporaryRoot = string(tempname);
mkdir(temporaryRoot);
cleanupObj = onCleanup(@() remove_temporary_root(temporaryRoot));

dataDir = fullfile(temporaryRoot, "data");
nestedDir = fullfile(dataDir, "nested");
mkdir(dataDir);
mkdir(nestedDir);
write_test_file(fullfile(dataDir, "root.csv"), uint8(char("root-input")));
write_test_file(fullfile(nestedDir, "nested.bin"), uint8(0:31));
write_test_file(fullfile(nestedDir, "README.md"), uint8(char("placeholder")));

caseConfig = struct();
caseConfig.name = "provenance_smoke";
caseConfig.dataDir = dataDir;
caseData = ProjectName_utils.io.load_case_inputs(caseConfig);

assert(numel(caseData.inputFiles) == 2, ...
    "Recursive discovery must include two non-placeholder input files.");
relativePaths = [caseData.inputFileRecords.relativePath];
assert(isequal(relativePaths, ["nested/nested.bin", "root.csv"]), ...
    "Input records must use sorted, platform-neutral relative paths.");
assert(all(strlength([caseData.inputFileRecords.sha256]) == 64), ...
    "Each input record must contain a SHA-256 digest.");
assert(strlength(caseData.dataVersionFingerprint) == 64, ...
    "The data version fingerprint must contain a SHA-256 digest.");
assert(caseData.dataVersion.fileCount == 2, ...
    "The data version must exclude README placeholders.");

trackerCommand = ...
    "tracker = ProjectName_utils.workflow.create_step_tracker(2, ""tracker_smoke"", ""UseInline"", false);" + ...
    "tracker.update(1, ""First step"");" + ...
    "tracker.fail(MException(""ProjectName:test:Expected"", ""expected failure""));";
trackerOutput = evalc(trackerCommand);
assert(contains(trackerOutput, "Workflow failed"), ...
    "A failed tracker must print its failed outcome.");
assert(~contains(trackerOutput, "Workflow finished"), ...
    "A failed tracker must not print a completed outcome.");

successResultDir = fullfile(temporaryRoot, "result", "success_case");
successFigureDir = fullfile(successResultDir, "figures");
mkdir(successFigureDir);
successConfig = struct( ...
    "projectRoot", temporaryRoot, ...
    "name", "success_case", ...
    "network", "smoke_network", ...
    "description", "Run-manifest success smoke", ...
    "entryFunction", "success_case", ...
    "seed", 11, ...
    "dataDir", dataDir, ...
    "cacheDir", fullfile(temporaryRoot, "cache", "success_case"), ...
    "resultDir", successResultDir, ...
    "figureDir", successFigureDir, ...
    "claim", "C_RUN_SUCCESS", ...
    "evidenceId", "E_RUN_SUCCESS", ...
    "contractVersion", "2026.07.12", ...
    "lifecycleStage", "one-to-hundred-evidence", ...
    "caseContract", "new-method", ...
    "figurePlanId", "FP-RUN-SUCCESS", ...
    "optimizerPriority", "not_applicable", ...
    "workflowStatus", "scaffold");
runState = struct( ...
    "startedAt", "2026-01-01 00:00:00", ...
    "rngSeed", 11, ...
    "rngType", "twister", ...
    "warnings", strings(0, 1));
stageResult = struct("status", "scaffold", "files", strings(0, 1), ...
    "warnings", strings(0, 1));
outputFiles = struct( ...
    "summaryFile", fullfile(successResultDir, "summary.txt"), ...
    "manifestFile", fullfile(successResultDir, "run_manifest.json"), ...
    "files", string(fullfile(successResultDir, "summary.txt")), ...
    "warnings", strings(0, 1));
write_test_file(outputFiles.summaryFile, uint8(char("summary")));
write_test_file(outputFiles.manifestFile, uint8(char("stale manifest")));

runSummary = ProjectName_utils.workflow.finalize_case_run( ...
    successConfig, runState, caseData, stageResult, stageResult, ...
    stageResult, outputFiles, stageResult);
successManifest = jsondecode(fileread(outputFiles.manifestFile));
assert(string(runSummary.status) == "scaffold", ...
    "A scaffold success run must retain its scaffold status.");
assert(string(successManifest.status) == "scaffold", ...
    "The success manifest must replace stale content with valid JSON.");
assert(string(successManifest.inputs.dataVersionFingerprint) == ...
        caseData.dataVersionFingerprint, ...
    "The success manifest must preserve the recursive input fingerprint.");
assert(string(successManifest.contractVersion) == "2026.07.12" && ...
        string(successManifest.lifecycleStage) == "one-to-hundred-evidence" && ...
        string(successManifest.caseContract) == "new-method" && ...
        string(successManifest.figurePlanId) == "FP-RUN-SUCCESS", ...
    "The run manifest must preserve lifecycle and handoff contract fields.");

directoryManifest = fullfile(temporaryRoot, "manifest_as_directory");
mkdir(directoryManifest);
directoryOutputFiles = outputFiles;
directoryOutputFiles.manifestFile = directoryManifest;
assert_throws(@() ProjectName_utils.workflow.finalize_case_run( ...
    successConfig, runState, caseData, stageResult, stageResult, ...
    stageResult, directoryOutputFiles, stageResult), ...
    "ProjectName_utils:workflow:ManifestPathIsDirectory");

failureResultDir = fullfile(temporaryRoot, "result", "failure_case");
failureFigureDir = fullfile(failureResultDir, "figures");
mkdir(failureFigureDir);
failureConfig = successConfig;
failureConfig.name = "failure_case";
failureConfig.entryFunction = "failure_case";
failureConfig.resultDir = failureResultDir;
failureConfig.figureDir = failureFigureDir;
failureConfig.dataDir = fullfile(temporaryRoot, "missing_data");
failureStage = struct("index", 3, "name", "Load and validate data inputs");
failureContext = struct( ...
    "invokedAt", "2026-01-01 00:00:00", ...
    "runState", runState, ...
    "caseData", struct(), ...
    "proposedResults", struct(), ...
    "baselineResults", struct(), ...
    "metrics", struct(), ...
    "outputFiles", struct(), ...
    "figureOutputs", struct());
try
    error("ProjectName:test:IntentionalFailure", "intentional failure");
catch expectedError
    failureManifestFile = ProjectName_utils.workflow.finalize_failed_case_run( ...
        failureConfig, failureStage, expectedError, failureContext);
end
failureManifest = jsondecode(fileread(failureManifestFile));
assert(string(failureManifest.status) == "failed", ...
    "A failed run must write a failed manifest.");
assert(failureManifest.failedStage.index == 3 && ...
        string(failureManifest.failure.identifier) == ...
        "ProjectName:test:IntentionalFailure", ...
    "The failed manifest must preserve the failed stage and original error identifier.");
assert(~failureManifest.inputs.dataDirExists, ...
    "The failed manifest must record a missing input directory.");
assert(~isempty(failureManifest.failure.stack), ...
    "The failed manifest must preserve the original exception stack.");
assert_throws(@() ProjectName_utils.workflow.assert_stage_ready( ...
    struct("status", "failed"), 4, "Run the proposed method"), ...
    "ProjectName_utils:workflow:StageReportedFailure");
assert_throws(@() ProjectName_utils.workflow.assert_stage_ready( ...
    struct("status", "running"), 4, "Run the proposed method"), ...
    "ProjectName_utils:workflow:StageNotTerminal");

failedStageResult = stageResult;
failedStageResult.status = "failed";
failedRunSummary = ProjectName_utils.workflow.finalize_case_run( ...
    successConfig, runState, caseData, failedStageResult, stageResult, ...
    stageResult, outputFiles, stageResult);
assert(string(failedRunSummary.status) == "failed" && ...
        ~contains(string(failedRunSummary.message), "Workflow completed"), ...
    "A failed stage status must not produce a completed run-summary message.");

gitRoot = fullfile(temporaryRoot, "git_status_smoke");
mkdir(gitRoot);
trackedFile = fullfile(gitRoot, "tracked.txt");
write_test_file(trackedFile, uint8(char("initial")));
run_git_smoke(gitRoot, "init -q");
run_git_smoke(gitRoot, "add tracked.txt");
run_git_smoke(gitRoot, ...
    "-c user.name=Smoke -c user.email=smoke@example.invalid commit -qm initial");
write_test_file(trackedFile, uint8(char("modified")));
gitOutputFiles = outputFiles;
gitOutputFiles.manifestFile = fullfile(successResultDir, "git_status_manifest.json");
gitConfig = successConfig;
gitConfig.projectRoot = gitRoot;
ProjectName_utils.workflow.finalize_case_run( ...
    gitConfig, runState, caseData, stageResult, stageResult, ...
    stageResult, gitOutputFiles, stageResult);
gitManifest = jsondecode(fileread(gitOutputFiles.manifestFile));
assert(startsWith(string(gitManifest.git.statusShort), " M tracked.txt"), ...
    "The run manifest must preserve the leading XY space in git status --short.");

entryFunctions = ["ProjectName_case33bw", "ProjectName_case123"];
for entryIndex = 1:numel(entryFunctions)
    entryFunction = entryFunctions(entryIndex);
    entryRoot = fullfile(temporaryRoot, "entry_success_" + string(entryIndex));
    mkdir(entryRoot);
    mkdir(fullfile(entryRoot, "data"));
    entryOutput = evalc("entrySummary = feval(char(entryFunction), entryRoot);");
    assert(string(entrySummary.status) == "scaffold" && ...
            contains(entryOutput, "Workflow finished"), ...
        "The formal case entry %s must complete its isolated scaffold run.", ...
        entryFunction);
    entryManifestFile = fullfile(entryRoot, "result", ...
        erase(entryFunction, "ProjectName_"), "run_manifest.json");
    entryManifest = jsondecode(fileread(entryManifestFile));
    assert(string(entryManifest.status) == "scaffold", ...
        "The formal case entry %s must write a success manifest.", entryFunction);

    failureRoot = fullfile(temporaryRoot, "entry_failure_" + string(entryIndex));
    mkdir(failureRoot);
    [failureOutput, entryError] = capture_entry_failure(entryFunction, failureRoot);
    assert(~isempty(entryError) && ...
            string(entryError.identifier) == "ProjectName_utils:io:MissingDataDir", ...
        "The formal case entry %s must rethrow its original input error.", ...
        entryFunction);
    assert(contains(failureOutput, "Workflow failed") && ...
            ~contains(failureOutput, "Workflow finished"), ...
        "The formal case entry %s must report failure without a completion line.", ...
        entryFunction);
    failureEntryManifest = jsondecode(fileread(fullfile(failureRoot, "result", ...
        erase(entryFunction, "ProjectName_"), "run_manifest.json")));
    assert(string(failureEntryManifest.status) == "failed" && ...
            failureEntryManifest.failedStage.index == 3 && ...
            string(failureEntryManifest.failure.identifier) == ...
            "ProjectName_utils:io:MissingDataDir", ...
        "The formal case entry %s must persist stage-3 failure provenance.", ...
        entryFunction);
end

fprintf("RUN_CONTRACT_SMOKE_OK\n");
end

function write_test_file(filePath, bytes)
fid = fopen(filePath, "wb");
assert(fid >= 0, "Could not create smoke-test file: %s", filePath);
cleanupObj = onCleanup(@() close_if_open(fid));
fwrite(fid, bytes, "uint8");
end

function close_if_open(fid)
if ~isempty(fopen(fid))
    fclose(fid);
end
end

function assert_throws(action, expectedIdentifier)
didThrow = false;
try
    action();
catch caughtError
    didThrow = true;
    assert(string(caughtError.identifier) == string(expectedIdentifier), ...
        "Expected error %s but received %s.", ...
        expectedIdentifier, caughtError.identifier);
end
assert(didThrow, "Expected error %s was not raised.", expectedIdentifier);
end

function [capturedOutput, caughtError] = capture_entry_failure(entryFunction, projectRoot) %#ok<INUSD>
caughtError = [];
capturedOutput = evalc( ...
    "try; feval(char(entryFunction), projectRoot); catch caughtError; end");
end

function run_git_smoke(projectRoot, argumentsText)
command = sprintf('git -C "%s" %s', char(projectRoot), char(argumentsText));
[statusCode, commandOutput] = system(command);
assert(statusCode == 0, "Git smoke setup failed: %s", commandOutput);
end

function remove_temporary_root(temporaryRoot)
if isfolder(temporaryRoot)
    rmdir(temporaryRoot, "s");
end
end
