function smoke_figure_profile()
%SMOKE_FIGURE_PROFILE Check the default IEEE figure profile and export path.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(projectRoot);

profile = ProjectName_utils.plotting.figure_profile("ieee");
assert(profile.name == "IEEE", "Expected IEEE to be the default figure profile.");
assert(abs(profile.singleColumnWidthCm - 8.89) < 0.02, ...
    "IEEE single-column width should be close to 3.5 inches.");
assert(profile.fontSizePt == 10, "Default formal figure font size should be 10 pt.");
assert(profile.minFontSizePt == 8, "Complex small figures may use 8 pt.");
assert(abs(profile.maxWidthCm - profile.singleColumnWidthCm) < 0.02, ...
    "Default formal figure width should not exceed one IEEE column.");

wideFig = ProjectName_utils.plotting.create_figure("double-column", ...
    "Profile", "ieee");
widePosition = wideFig.Position;
assert(widePosition(3) <= profile.singleColumnWidthCm + 0.02, ...
    "Default IEEE profile should clamp double-column requests to one column.");
close(wideFig);

fig = ProjectName_utils.plotting.create_figure("single-column", ...
    "Profile", "ieee", ...
    "AspectRatio", 0.65);
ax = axes(fig);
x = (1:5)';
y = [1; 2; 1.5; 2.5; 3];
h = ProjectName_utils.plotting.plot_method_line(ax, x, y, "proposed");
xlabel(ax, "Sample index");
ylabel(ax, "Metric (p.u.)");
legendHandle = ProjectName_utils.plotting.place_legend(ax);
assert(string(h.DisplayName) == "本文方法", ...
    "plot_method_line should use the Chinese methodStyle label as DisplayName.");
assert(string(legendHandle.Location) == "best", ...
    "Formal line figures should default to an in-axes best legend location.");
assert(string(legendHandle.Box) == "off", ...
    "Formal legends should default to a compact box-off style.");

styles = ProjectName_utils.plotting.methodStyle();
assert(string(styles.proposed_original.label) == "本文原始方法", ...
    "Ablation figures should have a short original-method label.");
assert(string(styles.proposed_without_network_constraints.label) == "去掉网络物理约束", ...
    "Ablation labels should be short and explicit.");
assert(string(styles.pappu2017.label) == "Pappu2017", ...
    "External SOTA labels should use compact author-year names.");

plotData = table(x, y, 'VariableNames', {'sampleIndex', 'metricPu'});
metadata = struct( ...
    "figNo", "FigSmoke", ...
    "contractVersion", "2026.07.12", ...
    "figurePlanId", "FP-SMOKE-PROFILE", ...
    "claimId", "C_SMOKE_PROFILE", ...
    "sciQuestion", "Does the default IEEE figure profile export a traceable bundle?", ...
    "physicsReproduction", "The plotted method curve should be tied to a declared physical reference before comparison claims.", ...
    "evidenceRole", "physical-reproduction", ...
    "dataFiles", "generated in tests/smoke_figure_profile.m", ...
    "dataDescription", "sampleIndex is unitless; metricPu is per-unit.", ...
    "visualEncoding", ProjectName_utils.plotting.methodStyle(), ...
    "targetLayout", "single-column", ...
    "command", "tests/smoke_figure_profile", ...
    "keyParams", struct("profile", "ieee"), ...
    "randomSeed", "not_applicable");

outDir = tempname;
mkdir(outDir);
outputs = ProjectName_utils.plotting.save_figure(fig, outDir, ...
    "FigSmoke_ieee_profile", ...
    "Metadata", metadata, ...
    "PlotData", plotData, ...
    "CloseFigure", false);

figPosition = fig.Position;
assert(figPosition(3) <= profile.singleColumnWidthCm + 0.02, ...
    "Exported formal figure width should not exceed one IEEE column.");
assert(abs(ax.FontSize - 10) < 0.1, ...
    "Exported formal figure text should be 10 pt by default.");

assert(exist(outputs.figFile, "file") == 2, "FIG export is missing.");
assert(exist(outputs.pngFile, "file") == 2, "PNG export is missing.");
assert(exist(outputs.svgFile, "file") == 2, "SVG export is missing.");
assert(exist(outputs.plotDataFile, "file") == 2, "Plot-data CSV export is missing.");
assert(any(endsWith(outputs.extraFiles, ".pdf")), "Default IEEE PDF export is missing.");
assert(exist(outputs.manifestFile, "file") == 2, "Figure manifest is missing.");
assert(exist(outputs.checkReportFile, "file") == 2, "Figure check report is missing.");
close(fig);

smallFig = ProjectName_utils.plotting.create_figure("single-column", ...
    "Profile", "ieee", ...
    "AspectRatio", 0.65);
smallAx = axes(smallFig);
ProjectName_utils.plotting.plot_method_line(smallAx, x, y, "proposed");
smallLegend = ProjectName_utils.plotting.place_legend(smallAx);
smallMetadata = metadata;
smallMetadata.figNo = "FigSmokeSmall";
smallMetadata.keyParams = struct("profile", "ieee", "fontSizePt", 8);
smallOutputs = ProjectName_utils.plotting.save_figure(smallFig, outDir, ...
    "FigSmoke_ieee_profile_small_font", ...
    "Metadata", smallMetadata, ...
    "PlotData", plotData, ...
    "FontSizePt", 8, ...
    "CloseFigure", false);
assert(abs(smallAx.FontSize - 8) < 0.1, ...
    "Complex small figures should use explicitly requested 8 pt text.");
assert(abs(smallLegend.FontSize - 8) < 0.1, ...
    "Complex small figures should apply the requested font size to legends.");
assert(exist(smallOutputs.manifestFile, "file") == 2, ...
    "Small-font figure manifest is missing.");
close(smallFig);
end
