function smoke_figure_profile()
%SMOKE_FIGURE_PROFILE Check the default IEEE figure profile and export path.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(projectRoot);

profile = ProjectName_utils.plotting.figure_profile("ieee");
assert(profile.name == "IEEE", "Expected IEEE to be the default figure profile.");
assert(abs(profile.singleColumnWidthCm - 8.89) < 0.02, ...
    "IEEE single-column width should be close to 3.5 inches.");

fig = ProjectName_utils.plotting.create_figure("single-column", ...
    "Profile", "ieee", ...
    "AspectRatio", 0.65);
ax = axes(fig);
x = (1:5)';
y = [1; 2; 1.5; 2.5; 3];
plot(ax, x, y, "LineWidth", 0.5, "Marker", "o");
xlabel(ax, "Sample index");
ylabel(ax, "Metric (p.u.)");

plotData = table(x, y, 'VariableNames', {'sampleIndex', 'metricPu'});
metadata = struct( ...
    "figNo", "FigSmoke", ...
    "sciQuestion", "Does the default IEEE figure profile export a traceable bundle?", ...
    "dataFiles", "generated in tests/smoke_figure_profile.m", ...
    "dataDescription", "sampleIndex is unitless; metricPu is per-unit.", ...
    "visualEncoding", ProjectName_utils.plotting.methodStyle(), ...
    "targetLayout", "single-column", ...
    "command", "tests/smoke_figure_profile", ...
    "keyParams", struct("profile", "ieee"), ...
    "randomSeed", "not_applicable");

outDir = tempname;
mkdir(outDir);
outputs = ProjectName_utils.plotting.save_figure(fig, outDir, ...
    "FigSmoke_ieee_profile", ...
    "Metadata", metadata, ...
    "PlotData", plotData);

assert(exist(outputs.figFile, "file") == 2, "FIG export is missing.");
assert(exist(outputs.pngFile, "file") == 2, "PNG export is missing.");
assert(exist(outputs.svgFile, "file") == 2, "SVG export is missing.");
assert(exist(outputs.plotDataFile, "file") == 2, "Plot-data CSV export is missing.");
assert(any(endsWith(outputs.extraFiles, ".pdf")), "Default IEEE PDF export is missing.");
assert(exist(outputs.manifestFile, "file") == 2, "Figure manifest is missing.");
assert(exist(outputs.checkReportFile, "file") == 2, "Figure check report is missing.");
end
