function s = methodStyle(name)
%METHODSTYLE Project-level visual encoding for paper figures.
%
% Replace the template labels before generating formal manuscript figures.
% Default labels are Chinese placeholders so the physical role is readable
% during project development. Keep registry keys in ASCII for stable MATLAB
% calls, and translate labels after the manuscript language is fixed.

registry = default_registry();

if nargin < 1 || isempty(name) || strlength(string(name)) == 0
    s = registry;
    return
end

key = char(lower(string(name)));
if isfield(registry, key)
    s = registry.(key);
else
    error("ProjectName_utils:plotting:UnknownMethodStyle", ...
        "Unregistered method style: %s. Add it to methodStyle before plotting.", name);
end
end

function registry = default_registry()
registry = struct();
registry.proposed = struct("label", "本文方法", "group", "proposed", ...
    "color", [0.85 0.10 0.10], "ls", "-", "mk", "s", ...
    "gray", 0.20, "hatch", "/");
registry.proposed_original = struct("label", "本文原始方法", "group", "proposed_ablation", ...
    "color", [0.85 0.10 0.10], "ls", "-", "mk", "s", ...
    "gray", 0.20, "hatch", "/");
registry.baseline = struct("label", "基准解（高精度仿真参考）", "group", "baseline", ...
    "color", [0 0 0], "ls", "-", "mk", "o", ...
    "gray", 0.15, "hatch", "none");
registry.pappu2017 = struct("label", "Pappu2017", "group", "external_sota", ...
    "color", [0.00 0.20 0.70], "ls", "--", "mk", "^", ...
    "gray", 0.45, "hatch", "\");
registry.author2021 = struct("label", "Author2021", "group", "external_sota", ...
    "color", [0.10 0.55 0.20], "ls", ":", "mk", "d", ...
    "gray", 0.65, "hatch", "x");
registry.proposed_without_network_constraints = struct("label", "去掉网络物理约束", ...
    "group", "proposed_ablation", "color", [0.85 0.10 0.10], ...
    "ls", "--", "mk", "v", "gray", 0.55, "hatch", ".");
registry.proposed_without_uncertainty_model = struct("label", "去掉源荷不确定性建模", ...
    "group", "proposed_ablation", "color", [0.85 0.10 0.10], ...
    "ls", "-.", "mk", "x", "gray", 0.75, "hatch", "+");
end
